name: Deploy with Ansible

on:
  release:
    types: [published, prereleased, edited]

permissions:
  contents: read

concurrency:
  group: deploy-rilis
  cancel-in-progress: true

jobs:
  deploy-production:
    if: |
      github.event.release.target_commitish == 'main' &&
      github.event.release.prerelease == false &&
      (github.event.action == 'published' || github.event.action == 'edited')
    name: Deploy (Release)
    runs-on: ubuntu-latest

    steps:
      - name: Debug Release Info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Release Action: ${{ github.event.action }}"
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Pre-release: ${{ github.event.release.prerelease }}"
          echo "Target Commitish: ${{ github.event.release.target_commitish }}"

  deploy-prerelease:
    if: |
      github.event.release.target_commitish == 'main' &&
      github.event.release.prerelease == true &&
      (github.event.action == 'prereleased' || github.event.action == 'published' || github.event.action == 'edited')
    name: Deploy (Pre-Release)
    runs-on: ubuntu-latest

    steps:
      - name: Debug Release Info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Release Action: ${{ github.event.action }}"
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Pre-release: ${{ github.event.release.prerelease }}"
          echo "Target Commitish: ${{ github.event.release.target_commitish }}"
